// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz0GDL3KLONb4FBA-dba5WFTad2XRbulA',
    appId: '1:794872075735:web:db56637b6a53e119baa792',
    messagingSenderId: '794872075735',
    projectId: 'firbase-app1',
    authDomain: 'firbase-app1.firebaseapp.com',
    storageBucket: 'firbase-app1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpQU44Xbq07nZbbwyMr2qWGBukLQNhImw',
    appId: '1:794872075735:android:285fcfb7d827a4eabaa792',
    messagingSenderId: '794872075735',
    projectId: 'firbase-app1',
    storageBucket: 'firbase-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhjXKL1pcH0q-EvkOP9Q1KUhgkGHKBS7Y',
    appId: '1:794872075735:ios:fd1d9489c5a2df78baa792',
    messagingSenderId: '794872075735',
    projectId: 'firbase-app1',
    storageBucket: 'firbase-app1.appspot.com',
    iosBundleId: 'com.example.firbaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhjXKL1pcH0q-EvkOP9Q1KUhgkGHKBS7Y',
    appId: '1:794872075735:ios:3042229566e381b1baa792',
    messagingSenderId: '794872075735',
    projectId: 'firbase-app1',
    storageBucket: 'firbase-app1.appspot.com',
    iosBundleId: 'com.example.firbaseApp.RunnerTests',
  );
}
